apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-develop
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: test-develop
  template:
    metadata:
      labels:
        app: test-develop
    spec:
      containers:
      - image: cmarcoux/test-argo:develop
        name: test-develop
        ports:
        - containerPort: 80
